### ISSUE TITLE
Onboard connectors

### ISSUE THREAD

**Issue by SHaaD94** [observIQ/observiq-otel-collector#1137]
Hi guys.

First of all thanks a lot for great collector distribution.

In `contrib` collector there is a `connector` functionality available.

Althougt it is current in development phase it would be great to have it in this distribution.

**Comment by SHaaD94** [comment]
@cpheps, any way I could help?

**Comment by cpheps** [comment]
@SHaaD94 I've actually got this on my list for today. I think it's simple enough to get it into our next relesae.
