### ISSUE TITLE
Bring install script into line with the one for BPOP

### ISSUE THREAD

**Issue by Dylan-M** [observIQ/observiq-otel-collector#934]
This is a two part issue to create parity among our products.

1. Add support for --file flag to install from a local rpm or deb file
2. Create file name parity for the install scripts for *NIX machines. BPOP is install_linux.sh and the collector is install_unix.sh, and they should really be the same name

The first part is extremely important for doing offline installs using the script in locked down environments

**Comment by cpheps** [comment]
@Dylan-M I think adding a `--file` flag makes sense. 

We're going to keep the name of the script the same though. It's hardcoded into BPOP for installation and changing the name also means if you want to use a specific version of the script you need to know what the name of the script was for that version. I think the risk of a disjointed experience isn't worth changing the name just for the sake of uniformity.

**Comment by BinaryFissionGames** [comment]
Agreed on the `--file` flag.

In the interim, a file URL can be specified with the -l flag to install using a local package, if needed. e.g.
```sh
sudo ./install_unix.sh -l "file:///home/user/observiq-otel-collector_v1.18.0_linux_amd64.deb"
```

**Comment by BinaryFissionGames** [comment]
@cpheps Are we considering this complete with #937 being merged?

**Comment by cpheps** [comment]
@BinaryFissionGames yeah I thought it would close this issue with the keyword.
